# Generated by Django 5.2.9 on 2026-02-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_comment_text_en_comment_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
    ]
